modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Warps/issues"

[[mods]]
    modId="project_essentials_warps"
    version="${file.jarVersion}"
    displayName="Project Essentials Warps"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Warps/MC-1.14.4/updatev2.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Warps"
    credits="hujle, JetBrains, all forge developers, and other contributors"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Share the ender portal with players! Adds the ability to control public
    points in different worlds.
    '''

[[dependencies.projectessentialswarps]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialswarps]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialswarps]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
